# Generated by Django 3.2.3 on 2021-06-14 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='variation',
            new_name='variation_category',
        ),
    ]
